server:
  port: 8085



spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


  thymeleaf:
    prefix: classpath:/views/
    suffix: .html


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.srj.web.stock
  configuration:
    map-underscore-to-camel-case: true
  notEmpty: true

#打印SQL
logging:
  level:
    #com.srj.web.sys.mapper: DEBUG
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  #RequestMappingHandlerMapping: trace


#file文件路径
filepath:
  download: C:/tool/models/
  upload: C:/tool/files/
  temp: C:/tool/temp/
